[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
srwa_factory = "5suWp35g2vbxzRCTW2fRACD32DaL9Q3wy72Cxz4AesLg"
srwa_controller = "A6JtsR3Zw1GB1gTJuqdpFiBijarm9pQRTgqVkZaEdBs3"
identity_claims = "AuUzmKAAVyvR6NvDdd56SDjXHSE8dUePEnC5moECw9mE"
compliance_modules = "GD3ArP1GPKN9sWYPxiPia2i3iAKKsnbXxpcoB1gQK5D"
offering_pool = "4D54H4NBA9Q7WtsAy2yaFs9BjEdT8DcdmXekKsf7n6KP"
yield_adapter = "4RrVh2CZKUiU3g7uD2qVtVMYbXSvMQ1oSz2S8RnuHpEv"
valuation_oracle = "C4sJ1phqCh2MxFJJqVHZuddXbp6hWfvz29N4CkscPpaW"
cashflow_engine = "4ySjU9NzSwg457oxWCVgaH3fqqrhh7iDQco7Db1Zq4Di"
purchase_order = "43iQGS4Xyg6aGcpL52n7KurMm5eVNvQKEtgdPSxZwKPU"
pool_distribution = "GBhbrpXQWfGTK6MSpbUUCMYh5X6hT5WWC66PDuiGx6Fm"

[programs.devnet]
srwa_factory = "5suWp35g2vbxzRCTW2fRACD32DaL9Q3wy72Cxz4AesLg"
srwa_controller = "A6JtsR3Zw1GB1gTJuqdpFiBijarm9pQRTgqVkZaEdBs3"
identity_claims = "AuUzmKAAVyvR6NvDdd56SDjXHSE8dUePEnC5moECw9mE"
compliance_modules = "GD3ArP1GPKN9sWYPxiPia2i3iAKKsnbXxpcoB1gQK5D"
offering_pool = "4D54H4NBA9Q7WtsAy2yaFs9BjEdT8DcdmXekKsf7n6KP"
yield_adapter = "4RrVh2CZKUiU3g7uD2qVtVMYbXSvMQ1oSz2S8RnuHpEv"
valuation_oracle = "C4sJ1phqCh2MxFJJqVHZuddXbp6hWfvz29N4CkscPpaW"
cashflow_engine = "4ySjU9NzSwg457oxWCVgaH3fqqrhh7iDQco7Db1Zq4Di"
purchase_order = "43iQGS4Xyg6aGcpL52n7KurMm5eVNvQKEtgdPSxZwKPU"
pool_distribution = "GBhbrpXQWfGTK6MSpbUUCMYh5X6hT5WWC66PDuiGx6Fm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/temp-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
